spring.application.name=truthlens

server.port=8080

## GEMINI API
#api.gemini.key=AIzaSyB9o4CzBFBEQGxMYqqfzGU4RqUtjL30DKc
#api.gemini.url=https://generativelanguage.googleapis.com/v1/models/gemini-1.5-pro:generateContent

api.gemini.key=AIzaSyB9o4CzBFBEQGxMYqqfzGU4RqUtjL30DKc
api.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# GOOGLE FACT CHECK API
api.factcheck.key=AIzaSyBZIEF0aZGTS73-CXDFg9_LtXQojSBAHO4
api.factcheck.url=https://factchecktools.googleapis.com/v1alpha1/claims:search

# NEWS API
api.news.key=3a59e145e58e95807f8623832a8a9cd9
api.news.url=https://gnews.io/api/v4/search
