spring.application.name=truthlens

server.port=8080

api.gemini.key=${GEMINI_API_KEY}
api.factcheck.key=${FACTCHECK_API_KEY}
api.news.key=${GNEWS_API_KEY}



api.gemini.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

# GOOGLE FACT CHECK API

api.factcheck.url=https://factchecktools.googleapis.com/v1alpha1/claims:search

# NEWS API

api.news.url=https://gnews.io/api/v4/search
